"""Add project_members table

Revision ID: c66a0faade43
Revises: 77150e51fca9
Create Date: 2025-05-28 18:27:10.336197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66a0faade43'
down_revision = '77150e51fca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
